# ExtraGore Particle Group Configuration
# ------------------------------------------------------
# This file enables the creation of custom blood particle properties for various entities.
# Begin by uniquely naming each property group to effectively manage different settings.

# Particle Behavior Options:
# - Bounce: The particle will bounce off surfaces like a solid object.
# - Stick: The particle will stick to walls and other surfaces.
# - Magic: Some particles will fall to the ground while the majority will fly up to the sky.
# - None: The particle won't have any special effects.

# Particle Weight Options:
# - Heavy: The particle will sink to the bottom when it's underwater.
# - Light: The particle will float up to the top of the water.

# Particle State Options:
# - Liquid: The particle will get larger during its lifetime.
# - Solid: The particle will remain the same size all the time.

# Color Settings:
# Set an RGB color value to visually distinguish particles for various entities.

# How to Use:
# 1. Define a group with a name, including behavior, weight, state, color and entity values.
# 2. Example:
#    ["Color Group Name"]
#    behavior = Choose from "Stuck", "Bounce" or "None"
#    weight = Choose from "Heavy" or "Light"
#    state = Choose from "Liquid" or "Solid"
#    color = "R,G,B"
#    entities = ["entityID1", "entityID2"]
# 3. You can modify or delete any predefined groups, except for the red group. The red group is non editable and serves only to show you unused entities which are compatible with different color groups.
# 4. Add your custom color groups under an already predefined group, except for the red one.
# 5. Ensure each color group has a unique name and is properly structured.

# Note: Incorrectly formatted lines or unrecognized entity IDs will be ignored.
# ------------------------------------------------------

["Violet Group"]
behavior = "Magic"
weight = "Light"
state = "Liquid"
color = "128,0,128"
entities = ["minecraft:enderman", "minecraft:endermite", "minecraft:phantom", "minecraft:shulker", "minecraft:silverfish", "minecraft:warden", "minecraft:ender_dragon"]

["White Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,255"
entities = ["minecraft:skeleton", "minecraft:ghast", "minecraft:iron_golem", "minecraft:skeleton_horse", "minecraft:snow_golem", "minecraft:stray", "minecraft:vex", "minecraft:wither_skeleton", "minecraft:allay", "minecraft:wither"]

["Green Group"]
behavior = "Stuck"
weight = "Light"
state = "Liquid"
color = "0,255,0"
entities = ["minecraft:cave_spider", "minecraft:creeper", "minecraft:slime", "minecraft:spider", "minecraft:witch"]

["Yellow Group"]
behavior = "Bounce"
weight = "Heavy"
state = "Solid"
color = "255,255,0"
entities = ["minecraft:blaze", "minecraft:magma_cube", "minecraft:strider"]

["Blue Group"]
behavior = "None"
weight = "Light"
state = "Liquid"
color = "0,0,255"
entities = ["minecraft:squid", "minecraft:elder_guardian", "minecraft:guardian", "minecraft:glow_squid"]

# Auto generated red color group - do not edit. Use this as reference for unused entity IDs.
"255,0,0" = [
    "cataclysm:maledictus",
    "cataclysm:coral_golem",
    "alexsmobs:snow_leopard",
    "alexsmobs:endergrade",
    "minecraft:horse",
    "the_deep_void:light",
    "boh:whiteface",
    "minecraft:llama",
    "the_deep_void:rotten_cult_member",
    "boh:facehugger",
    "alexsmobs:skreecher",
    "cataclysm:ender_guardian",
    "the_deep_void:gravekeeper",
    "cataclysm:deepling_warlock",
    "minecraft:tadpole",
    "boh:tamed_rat",
    "boh:ao_oni",
    "alexsmobs:hammerhead_shark",
    "alexsmobs:grizzly_bear",
    "boh:chucky_grab",
    "the_deep_void:tamed_alpha_bone_crawler",
    "alexsmobs:murmur_head",
    "boh:gold_hostile",
    "the_deep_void:summoned_charred_spike",
    "boh:demogorgon",
    "boh:sonic_exe",
    "jeffs_cursed_walking_structures:door_entity",
    "minecraft:mooshroom",
    "the_deep_void:built_big_overseer_pillar",
    "minecraft:axolotl",
    "the_deep_void:rooted_clone",
    "ad_astra:martian_raptor",
    "the_deep_void:ghostly_nightmare",
    "alexsmobs:gorilla",
    "alexsmobs:cosmic_cod",
    "the_deep_void:void_dweller",
    "the_deep_void:thrown_soul_seeker",
    "alexsmobs:kangaroo",
    "duckling:quackling",
    "ecologics:coconut_crab",
    "bloomingnature:termite",
    "alexsmobs:hummingbird",
    "iceandfire:siren",
    "mutantmonsters:mutant_zombie",
    "boh:swamp_monster",
    "ad_astra:sulfur_creeper",
    "alexsmobs:crow",
    "jeffs_cursed_walking_structures:boss_spawner",
    "boh:james_sunderland",
    "alexsmobs:guster",
    "the_deep_void:cathedral_ghost",
    "boh:michael_davies",
    "bloomingnature:wandering_gardener",
    "cataclysm:koboleton",
    "minecraft:chicken",
    "alexsmobs:giant_squid",
    "minecraft:zombie",
    "iceandfire:dread_knight",
    "the_deep_void:small_flesh_cube",
    "alexsmobs:emu",
    "ad_astra:glacian_ram",
    "the_deep_void:shadow",
    "alexsmobs:flutter",
    "minecraft:hoglin",
    "boh:vampire_bat",
    "iceandfire:myrmex_swarmer",
    "minecraft:zombified_piglin",
    "the_deep_void:eyekin_flying",
    "minecraft:sheep",
    "the_deep_void:centigaze_hidden",
    "skyfall:meteorite_1_ancient_debris",
    "alexsmobs:bone_serpent_part",
    "alexsmobs:raccoon",
    "minecraft:ravager",
    "alexsmobs:bone_serpent",
    "iceandfire:myrmex_soldier",
    "skyfall:meteorite_2_stone",
    "boh:simonhenriksson",
    "boh:martian_drone",
    "iceandfire:pixie",
    "boh:chestburster",
    "alexsmobs:mudskipper",
    "iceandfire:myrmex_sentinel",
    "boh:jason_voorhees",
    "skyfall:meteorite_1_stone",
    "boh:decoy_dog",
    "alexsmobs:crimson_mosquito",
    "alexsmobs:jerboa",
    "the_deep_void:overseer_pillar",
    "cataclysm:netherite_ministrosity",
    "alexsmobs:comb_jelly",
    "the_deep_void:charred_spike",
    "the_deep_void:big_overseer",
    "boh:gold_lost",
    "ad_astra:zombified_mogler",
    "boh:six",
    "boh:book_simon",
    "the_deep_void:sulfur_tnt_entity",
    "alexsmobs:enderiophage",
    "alexsmobs:sunbird",
    "the_deep_void:licker",
    "the_deep_void:wanderer",
    "iceandfire:myrmex_worker",
    "minecraft:cat",
    "duckling:duck",
    "minecraft:tropical_fish",
    "cataclysm:the_prowler",
    "minecraft:zombie_villager",
    "alexsmobs:froststalker",
    "minecraft:giant",
    "boh:stiltwalker",
    "alexsmobs:lobster",
    "mowziesmobs:lantern",
    "alexsmobs:seagull",
    "boh:boiled_one",
    "skyfall:meteorite_2_skyrock",
    "ad_astra:corrupted_lunarian",
    "minecraft:husk",
    "the_deep_void:built_big_overseer",
    "mowziesmobs:umvuthana",
    "minecraft:donkey",
    "mowziesmobs:umvuthana_crane_player",
    "mutantmonsters:mutant_skeleton",
    "cataclysm:the_leviathan",
    "minecraft:piglin_brute",
    "the_deep_void:flesh_cube",
    "the_deep_void:rooted",
    "cataclysm:the_baby_leviathan",
    "skyfall:meteorite_2_pentafthalmos_egg",
    "boh:goji",
    "cataclysm:deepling_brute",
    "alexsmobs:frilled_shark",
    "alexsmobs:bald_eagle",
    "iceandfire:ice_dragon",
    "boh:specimen_9_boss",
    "alexsmobs:blobfish",
    "ecologics:squirrel",
    "boh:siren_head",
    "alexsmobs:void_worm",
    "minecraft:parrot",
    "boh:seed_eater",
    "the_deep_void:alpha_bone_crawler",
    "alexsmobs:centipede_head",
    "boh:saucer",
    "cataclysm:the_watcher",
    "iceandfire:sea_serpent",
    "alexsmobs:banana_slug",
    "mutantmonsters:mutant_creeper",
    "the_deep_void:built_overseer_pillar",
    "skyfall:angry_moon",
    "alexsmobs:bunfungus",
    "skyfall:meteorite_1_pentafthalmos_egg",
    "minecraft:mule",
    "minecraft:vindicator",
    "alexsmobs:flying_fish",
    "the_deep_void:centigaze",
    "boh:fuwatti",
    "cataclysm:nameless_sorcerer",
    "cataclysm:endermaptera",
    "cataclysm:lionfish",
    "cataclysm:coralssus",
    "jeffs_cursed_walking_structures:driller",
    "tombstone:grave_guardian",
    "jeffsgibbing:ribs",
    "boh:real_deer",
    "boh:predator_sight",
    "boh:phantom_puppet",
    "cataclysm:the_harbinger",
    "alexsmobs:terrapin",
    "boh:krampus",
    "boh:fresno_nightcrawler",
    "mowziesmobs:bluff",
    "iceandfire:lightning_dragon",
    "minecraft:pig",
    "alexsmobs:alligator_snapping_turtle",
    "boh:raatma",
    "boh:springtrap",
    "iceandfire:fire_dragon",
    "the_deep_void:bone_crawler",
    "ad_astra:pygro",
    "minecraft:cod",
    "boh:vampire",
    "the_deep_void:tiny_light",
    "boh:smile_dog",
    "alexsmobs:platypus",
    "skyfall:meteorite_1_gold_ore",
    "skyfall:meteorite_1_basalt",
    "minecraft:cow",
    "alexsmobs:rocky_roller",
    "boh:pyramid_head",
    "alexsmobs:soul_vulture",
    "the_deep_void:overseer",
    "the_deep_void:amalgam",
    "alexsmobs:blue_jay",
    "iceandfire:dread_scuttler",
    "boh:granny",
    "minecraft:salmon",
    "cataclysm:ignis",
    "mowziesmobs:naga",
    "boh:demon",
    "alexsmobs:anteater",
    "alexsmobs:rain_frog",
    "boh:jeff_the_killer",
    "mowziesmobs:ferrous_wroughtnaut",
    "minecraft:rabbit",
    "minecraft:pillager",
    "boh:saw_runner",
    "minecraft:zoglin",
    "the_deep_void:mother_bone_crawler",
    "boh:phantom_mangle",
    "alexsmobs:leafcutter_ant",
    "boh:torment_pyramid",
    "cataclysm:deepling_priest",
    "boh:deer_mimic",
    "iceandfire:gorgon",
    "cataclysm:ignited_revenant",
    "boh:sadako",
    "the_deep_void:roamer",
    "skyfall:target_particle",
    "alexsmobs:gazelle",
    "minecraft:sniffer",
    "boh:rabbid",
    "the_deep_void:spore_spewer",
    "iceandfire:cockatrice",
    "skyfall:shock_wave",
    "mowziesmobs:umvuthana_follower_player",
    "the_deep_void:eyekin",
    "iceandfire:deathworm",
    "cataclysm:modern_remnant",
    "ad_astra:mogler",
    "boh:neco_arc",
    "boh:ghostface_decoy",
    "alexsmobs:seal",
    "alexsmobs:roadrunner",
    "alexsmobs:laviathan",
    "minecraft:trader_llama",
    "boh:rolling_giant",
    "iceandfire:dread_lich",
    "the_deep_void:baby_bone_crawler_neutral",
    "alexsmobs:maned_wolf",
    "minecraft:dolphin",
    "alexsmobs:gelada_monkey",
    "boh:herobrine",
    "boh:tails",
    "boh:predator",
    "alexsmobs:dropbear",
    "alexsmobs:tiger",
    "minecraft:bee",
    "alexsmobs:devils_hole_pupfish",
    "the_deep_void:rotten_corpse",
    "minecraft:illusioner",
    "tombstone:spectral_wolf",
    "jeffsgibbing:gib_head_entity",
    "alexsmobs:bison",
    "mowziesmobs:foliaath",
    "mowziesmobs:frostmaw",
    "minecraft:drowned",
    "jeffsgibbing:gib_leg_entity",
    "alexsmobs:tusklin",
    "ad_astra:zombified_pygro",
    "alexsmobs:underminer",
    "minecraft:wandering_trader",
    "boh:eyeless_jack",
    "the_deep_void:muzzled_death_vulture",
    "the_deep_void:death_maw_hidden",
    "the_deep_void:nightmare",
    "the_deep_void:baby_bone_crawler",
    "iceandfire:stone_statue",
    "cataclysm:netherite_monstrosity",
    "cataclysm:wadjet",
    "hordes:drowned_player",
    "mowziesmobs:umvuthana_raptor",
    "minecraft:pufferfish",
    "boh:taken_pillar",
    "boh:big_daddy",
    "minecraft:fox",
    "the_deep_void:abductor",
    "skyfall:meteorite_1_skyrock",
    "mowziesmobs:umvuthana_crane",
    "boh:phantom_bb",
    "alexsmobs:warped_toad",
    "skyfall:pentafthalmos",
    "alexsmobs:cockroach",
    "cataclysm:elite_draugr",
    "boh:ghostface",
    "cataclysm:deepling_angler",
    "alexsmobs:capuchin_monkey",
    "boh:little_sister",
    "hordes:husk_player",
    "cataclysm:draugr",
    "boh:wendigo",
    "minecraft:polar_bear",
    "the_deep_void:big_eye",
    "minecraft:turtle",
    "the_deep_void:mourner",
    "boh:red",
    "boh:slender_man",
    "alexsmobs:rattlesnake",
    "the_deep_void:lurker",
    "boh:sotiris",
    "boh:chucky",
    "cataclysm:old_netherite_monstrosity",
    "alexsmobs:potoo",
    "alexsmobs:fly",
    "boh:werewolf",
    "boh:entity_well",
    "alexsmobs:straddler",
    "alexsmobs:sea_bear",
    "boh:xenomorph",
    "mowziesmobs:umvuthana_follower_raptor",
    "ad_astra:pygro_brute",
    "the_deep_void:big_light",
    "cataclysm:ender_golem",
    "alexsmobs:sugar_glider",
    "boh:mothman",
    "the_deep_void:death_maw",
    "alexsmobs:orca",
    "the_deep_void:stalker",
    "iceandfire:troll",
    "boh:celebi",
    "minecraft:bat",
    "alexsmobs:cosmaw",
    "iceandfire:amphithere",
    "the_deep_void:beholder",
    "the_deep_void:blind_prophet",
    "the_deep_void:damned",
    "alexsmobs:skunk",
    "cataclysm:deepling",
    "alexsmobs:tasmanian_devil",
    "the_deep_void:four_eyes",
    "cataclysm:ancient_remnant",
    "alexsmobs:stradpole",
    "the_deep_void:overseer_big_pillar",
    "iceandfire:stymphalian_bird",
    "ecologics:penguin",
    "the_deep_void:death_vulture",
    "iceandfire:hippogryph",
    "the_deep_void:tamed_mother_bone_crawler",
    "ad_astra:lunarian_wandering_trader",
    "minecraft:panda",
    "boh:ben_drowned",
    "alexsmobs:moose",
    "alexsmobs:shoebill",
    "alexsmobs:farseer",
    "cataclysm:amethyst_crab",
    "the_deep_void:built_overseer",
    "the_deep_void:swarmer",
    "alexsmobs:warped_mosco",
    "hordes:zombie_player",
    "cataclysm:ancient_ancient_remnant",
    "iceandfire:cyclops",
    "boh:rexy",
    "jeffsgibbing:flesh_3",
    "jeffsgibbing:flesh_2",
    "boh:phantom_foxy",
    "alexsmobs:komodo_dragon",
    "boh:phantom_freddy",
    "the_deep_void:ghost",
    "cataclysm:ignited_berserker",
    "boh:taken_hands",
    "boh:souichi",
    "alexsmobs:crocodile",
    "the_deep_void:mrordyygothre",
    "boh:exe_monitor",
    "jeffs_cursed_walking_structures:spawnpoint_entity",
    "alexsmobs:triops",
    "the_deep_void:hallucination",
    "alexsmobs:rhinoceros",
    "boh:rat",
    "alexsmobs:mimicube",
    "skyfall:meteorite_1_iron_ore",
    "jeffsgibbing:flesh_entity",
    "ad_astra:lunarian",
    "minecraft:frog",
    "warrior:warrior",
    "alexsmobs:mimic_octopus",
    "alexsmobs:void_worm_part",
    "boh:ink_demon",
    "the_deep_void:cross_eyes",
    "boh:freddy_krueger",
    "boh:rake",
    "iceandfire:hydra",
    "the_deep_void:fool_eater",
    "the_deep_void:stalking_stalker",
    "minecraft:evoker",
    "iceandfire:dread_ghoul",
    "alexsmobs:tarantula_hawk",
    "alexsmobs:cachalot_whale",
    "boh:whiteface_friendly",
    "boh:phantom_chica",
    "iceandfire:dread_horse",
    "alexsmobs:anaconda",
    "the_deep_void:multiple_eyes",
    "boh:ghost",
    "boh:lifeform",
    "mowziesmobs:grottol",
    "the_deep_void:goo_spitter",
    "the_deep_void:devourer",
    "mowziesmobs:baby_foliaath",
    "minecraft:goat",
    "mutantmonsters:mutant_enderman",
    "iceandfire:dread_beast",
    "alexsmobs:mantis_shrimp",
    "mutantmonsters:spider_pig",
    "boh:ratazana",
    "mowziesmobs:umvuthi",
    "iceandfire:hippocampus",
    "skyfall:meteorite_3_skyrock",
    "alexsmobs:toucan",
    "iceandfire:myrmex_queen",
    "boh:unown_8",
    "boh:unown_7",
    "boh:unown_6",
    "boh:michael_myers",
    "iceandfire:ghost",
    "boh:unown_5",
    "boh:unown_4",
    "boh:unown_3",
    "boh:unown_2",
    "boh:unown_1",
    "iceandfire:myrmex_royal",
    "boh:unown_9",
    "ad_astra:star_crawler",
    "alexsmobs:murmur",
    "boh:nemesis",
    "the_deep_void:tamed_bone_crawler",
    "boh:gray_alien",
    "skyfall:meteorite_2_loot",
    "boh:deer",
    "iceandfire:dread_thrall",
    "alexsmobs:mungus",
    "the_deep_void:everhunger",
    "alexsmobs:caiman",
    "alexsmobs:spectre",
    "cataclysm:kobolediator",
    "alexsmobs:catfish",
    "mutantmonsters:endersoul_clone",
    "boh:unown_13",
    "boh:unown_12",
    "boh:unown_11",
    "minecraft:piglin",
    "boh:unown_10",
    "the_deep_void:falling_corpse",
    "boh:unown_15",
    "boh:light_head",
    "boh:unown_14",
    "alexsmobs:skelewag",
    "alexsmobs:elephant",
    "the_deep_void:scarecrow",
    "minecraft:zombie_horse",
    "minecraft:camel",
    "cataclysm:royal_draugr",
    "boh:jason_mask",
    "cataclysm:aptrgangr",
    "minecraft:ocelot",
    "jeffsgibbing:bone_entity",
    "minecraft:wolf",
    "boh:gaster"
]
